import { type ElementType } from './types';

export const startElemInPeriodicTableRows = [0, 2, 10, 18, 36, 54, 86, 118];
export const numElemsInPeriodicTableRows = [2, 8, 8, 18, 18, 32, 32, 32];

export const elements: ElementType[] = [
  {
    "name": "Hydrogen",
    "symbol": "H",
    "number": 1,
    "aMass": 1.00798,
    "amassunc": "(13)",
    "eConfig": "1s1",
    "density": "0.08988",
    "meltingPoint": "13.81",
    "boilingPoint": "20.28",
    "oxidationStates": "±1",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "3.04",
    "firstIonizationEnergy": "13.598",
    "valenceAtomicRadiusRDK": "52.90",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "154",
    "vanderWallRadius": "120",
    "metallicRadius": "N/A",
    "covalentRadius": "31",
    "valenceEffectiveNuclearChargeRDK": "1.00",
    "valenceEffectiveNuclearChargeGuerra": "1",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.1805",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Helium",
    "symbol": "He",
    "number": 2,
    "aMass": 4.002602,
    "amassunc": "(2)",
    "eConfig": "1s2",
    "density": "0.1785",
    "meltingPoint": "0.95",
    "boilingPoint": "4.22",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "4.42",
    "firstIonizationEnergy": "24.587",
    "valenceAtomicRadiusRDK": "31.27",
    "valenceAtomicRadiusClement": "31",
    "R001AtomicRadius": "134",
    "vanderWallRadius": "143",
    "metallicRadius": "N/A",
    "covalentRadius": "28",
    "valenceEffectiveNuclearChargeRDK": "1.69",
    "valenceEffectiveNuclearChargeGuerra": "1.618",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.1513",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Lithium",
    "symbol": "Li",
    "number": 3,
    "aMass": 6.967,
    "amassunc": "(30)",
    "eConfig": "1s2 2s1",
    "density": "0.534",
    "meltingPoint": "453.65",
    "boilingPoint": "1615",
    "oxidationStates": "1",
    "electronegativityPauling": "0.98",
    "electronegativityTandO": "2.17",
    "firstIonizationEnergy": "5.392",
    "valenceAtomicRadiusRDK": "163.76",
    "valenceAtomicRadiusClement": "167",
    "R001AtomicRadius": "220",
    "vanderWallRadius": "212",
    "metallicRadius": "152",
    "covalentRadius": "128",
    "valenceEffectiveNuclearChargeRDK": "1.29",
    "valenceEffectiveNuclearChargeGuerra": "1.55",
    "electricalConductivity": "1.1×10⁷",
    "thermalConductivity": "85",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Beryllium",
    "symbol": "Be",
    "number": 4,
    "aMass": 9.0121831,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2",
    "density": "1.85",
    "meltingPoint": "1560",
    "boilingPoint": "2744",
    "oxidationStates": "2",
    "electronegativityPauling": "1.57",
    "electronegativityTandO": "2.42",
    "firstIonizationEnergy": "9.323",
    "valenceAtomicRadiusRDK": "105.69",
    "valenceAtomicRadiusClement": "112",
    "R001AtomicRadius": "219",
    "vanderWallRadius": "198",
    "metallicRadius": "112",
    "covalentRadius": "96",
    "valenceEffectiveNuclearChargeRDK": "2.00",
    "valenceEffectiveNuclearChargeGuerra": "2.266",
    "electricalConductivity": "2.5×10⁷",
    "thermalConductivity": "190",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Boron",
    "symbol": "B",
    "number": 5,
    "aMass": 10.8135,
    "amassunc": "(75)",
    "eConfig": "1s2 2s2 2p1",
    "density": "2.37",
    "meltingPoint": "2348",
    "boilingPoint": "4273",
    "oxidationStates": "3",
    "electronegativityPauling": "2.04",
    "electronegativityTandO": "3.04",
    "firstIonizationEnergy": "8.298",
    "valenceAtomicRadiusRDK": "86.63",
    "valenceAtomicRadiusClement": "87",
    "R001AtomicRadius": "205",
    "vanderWallRadius": "191",
    "metallicRadius": "N/A",
    "covalentRadius": "85",
    "valenceEffectiveNuclearChargeRDK": "2.44",
    "valenceEffectiveNuclearChargeGuerra": "2.268",
    "electricalConductivity": "1×10⁻⁴",
    "thermalConductivity": "27",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Carbon",
    "symbol": "C",
    "number": 6,
    "aMass": 12.0106,
    "amassunc": "(10)",
    "eConfig": "1s2 2s2 2p2",
    "density": "2.267",
    "meltingPoint": "3823",
    "boilingPoint": "4098",
    "oxidationStates": "±4",
    "electronegativityPauling": "2.55",
    "electronegativityTandO": "3.15",
    "firstIonizationEnergy": "11.26",
    "valenceAtomicRadiusRDK": "66.82",
    "valenceAtomicRadiusClement": "67",
    "R001AtomicRadius": "190",
    "vanderWallRadius": "177",
    "metallicRadius": "N/A",
    "covalentRadius": "76",
    "valenceEffectiveNuclearChargeRDK": "3.17",
    "valenceEffectiveNuclearChargeGuerra": "2.916",
    "electricalConductivity": "1×10⁴",
    "thermalConductivity": "140",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Nitrogen",
    "symbol": "N",
    "number": 7,
    "aMass": 14.006855,
    "amassunc": "(425)",
    "eConfig": "1s2 2s2 2p3",
    "density": "1.2506",
    "meltingPoint": "63.15",
    "boilingPoint": "77.36",
    "oxidationStates": "±3,5",
    "electronegativityPauling": "3.04",
    "electronegativityTandO": "3.56",
    "firstIonizationEnergy": "14.534",
    "valenceAtomicRadiusRDK": "54.61",
    "valenceAtomicRadiusClement": "56",
    "R001AtomicRadius": "179",
    "vanderWallRadius": "166",
    "metallicRadius": "N/A",
    "covalentRadius": "71",
    "valenceEffectiveNuclearChargeRDK": "3.87",
    "valenceEffectiveNuclearChargeGuerra": "3.546",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.02583",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Oxygen",
    "symbol": "O",
    "number": 8,
    "aMass": 15.99940,
    "amassunc": "(37)",
    "eConfig": "1s2 2s2 2p4",
    "density": "1.429",
    "meltingPoint": "54.36",
    "boilingPoint": "90.2",
    "oxidationStates": "-2",
    "electronegativityPauling": "3.44",
    "electronegativityTandO": "3.78",
    "firstIonizationEnergy": "13.618",
    "valenceAtomicRadiusRDK": "46.93",
    "valenceAtomicRadiusClement": "48",
    "R001AtomicRadius": "171",
    "vanderWallRadius": "150",
    "metallicRadius": "N/A",
    "covalentRadius": "66",
    "valenceEffectiveNuclearChargeRDK": "4.51",
    "valenceEffectiveNuclearChargeGuerra": "4.022",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.02658",
    "crystallineStructure": "assets/BCM.png",
  },
  {
    "name": "Fluorine",
    "symbol": "F",
    "number": 9,
    "aMass": 18.998403162,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2 2p5",
    "density": "1.696",
    "meltingPoint": "53.53",
    "boilingPoint": "85.03",
    "oxidationStates": "-1",
    "electronegativityPauling": "3.98",
    "electronegativityTandO": "4",
    "firstIonizationEnergy": "17.423",
    "valenceAtomicRadiusRDK": "40.93",
    "valenceAtomicRadiusClement": "42",
    "R001AtomicRadius": "163",
    "vanderWallRadius": "146",
    "metallicRadius": "N/A",
    "covalentRadius": "57",
    "valenceEffectiveNuclearChargeRDK": "5.17",
    "valenceEffectiveNuclearChargeGuerra": "4.598",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.0277",
    "crystallineStructure": "assets/BCM.png",
  },
  {
    "name": "Neon",
    "symbol": "Ne",
    "number": 10,
    "aMass": 20.1797,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6",
    "density": "0.8999",
    "meltingPoint": "24.56",
    "boilingPoint": "27.07",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "4.44",
    "firstIonizationEnergy": "21.565",
    "valenceAtomicRadiusRDK": "36.23",
    "valenceAtomicRadiusClement": "38",
    "R001AtomicRadius": "156",
    "vanderWallRadius": "158",
    "metallicRadius": "N/A",
    "covalentRadius": "58",
    "valenceEffectiveNuclearChargeRDK": "5.84",
    "valenceEffectiveNuclearChargeGuerra": "5.175",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.0491",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Sodium",
    "symbol": "Na",
    "number": 11,
    "aMass": 22.98976928,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s1",
    "density": "0.97",
    "meltingPoint": "370.95",
    "boilingPoint": "1156",
    "oxidationStates": "1",
    "electronegativityPauling": "0.93",
    "electronegativityTandO": "2.15",
    "firstIonizationEnergy": "5.139",
    "valenceAtomicRadiusRDK": "216.95",
    "valenceAtomicRadiusClement": "190",
    "R001AtomicRadius": "225",
    "vanderWallRadius": "250",
    "metallicRadius": "186",
    "covalentRadius": "166",
    "valenceEffectiveNuclearChargeRDK": "2.19",
    "valenceEffectiveNuclearChargeGuerra": "3.211",
    "electricalConductivity": "2.1×10⁷",
    "thermalConductivity": "140",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Magnesium",
    "symbol": "Mg",
    "number": 12,
    "aMass": 24.3055,
    "amassunc": "(15)",
    "eConfig": "1s2 2s2 2p6 3s2",
    "density": "1.74",
    "meltingPoint": "923",
    "boilingPoint": "1363",
    "oxidationStates": "2",
    "electronegativityPauling": "1.31",
    "electronegativityTandO": "2.39",
    "firstIonizationEnergy": "7.646",
    "valenceAtomicRadiusRDK": "153.32",
    "valenceAtomicRadiusClement": "145",
    "R001AtomicRadius": "240",
    "vanderWallRadius": "251",
    "metallicRadius": "160",
    "covalentRadius": "141",
    "valenceEffectiveNuclearChargeRDK": "3.11",
    "valenceEffectiveNuclearChargeGuerra": "4.156",
    "electricalConductivity": "2.3×10⁷",
    "thermalConductivity": "160",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Aluminum",
    "symbol": "Al",
    "number": 13,
    "aMass": 26.9815384,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p1",
    "density": "2.7",
    "meltingPoint": "933.437",
    "boilingPoint": "2792",
    "oxidationStates": "3",
    "electronegativityPauling": "1.61",
    "electronegativityTandO": "2.52",
    "firstIonizationEnergy": "5.986",
    "valenceAtomicRadiusRDK": "148.37",
    "valenceAtomicRadiusClement": "118",
    "R001AtomicRadius": "239",
    "vanderWallRadius": "225",
    "metallicRadius": "143",
    "covalentRadius": "121",
    "valenceEffectiveNuclearChargeRDK": "3.21",
    "valenceEffectiveNuclearChargeGuerra": "3.642",
    "electricalConductivity": "3.8×10⁷",
    "thermalConductivity": "235",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Silicon",
    "symbol": "Si",
    "number": 14,
    "aMass": 28.085,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p2",
    "density": "2.3296",
    "meltingPoint": "1687",
    "boilingPoint": "3538",
    "oxidationStates": "±4",
    "electronegativityPauling": "1.9",
    "electronegativityTandO": "2.82",
    "firstIonizationEnergy": "8.152",
    "valenceAtomicRadiusRDK": "115.68",
    "valenceAtomicRadiusClement": "111",
    "R001AtomicRadius": "232",
    "vanderWallRadius": "219",
    "metallicRadius": "N/A",
    "covalentRadius": "111",
    "valenceEffectiveNuclearChargeRDK": "4.12",
    "valenceEffectiveNuclearChargeGuerra": "4.541",
    "electricalConductivity": "1.0×10³",
    "thermalConductivity": "150",
    "crystallineStructure": "assets/Diamond.png",
  },
  {
    "name": "Phosphorus",
    "symbol": "P",
    "number": 15,
    "aMass": 30.973761998,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2 2p6 3s2 3p3",
    "density": "1.82",
    "meltingPoint": "317.3",
    "boilingPoint": "553.65",
    "oxidationStates": "±3,5",
    "electronegativityPauling": "2.19",
    "electronegativityTandO": "3.16",
    "firstIonizationEnergy": "10.487",
    "valenceAtomicRadiusRDK": "96.08",
    "valenceAtomicRadiusClement": "98",
    "R001AtomicRadius": "223",
    "vanderWallRadius": "190",
    "metallicRadius": "N/A",
    "covalentRadius": "107",
    "valenceEffectiveNuclearChargeRDK": "4.96",
    "valenceEffectiveNuclearChargeGuerra": "5.376",
    "electricalConductivity": "1.0×10⁷",
    "thermalConductivity": "0.236",
    "crystallineStructure": "assets/T.png",
  },
  {
    "name": "Sulfur",
    "symbol": "S",
    "number": 16,
    "aMass": 32.0675,
    "amassunc": "(85)",
    "eConfig": "1s2 2s2 2p6 3s2 3p4",
    "density": "2.067",
    "meltingPoint": "388.36",
    "boilingPoint": "717.75",
    "oxidationStates": "±2,4,6",
    "electronegativityPauling": "2.58",
    "electronegativityTandO": "3.44",
    "firstIonizationEnergy": "10.36",
    "valenceAtomicRadiusRDK": "83.48",
    "valenceAtomicRadiusClement": "88",
    "R001AtomicRadius": "214",
    "vanderWallRadius": "189",
    "metallicRadius": "N/A",
    "covalentRadius": "105",
    "valenceEffectiveNuclearChargeRDK": "5.70",
    "valenceEffectiveNuclearChargeGuerra": "6.041",
    "electricalConductivity": "1.0×10⁻¹⁵",
    "thermalConductivity": "0.205",
    "crystallineStructure": "assets/FCO.png",
  },
  {
    "name": "Chlorine",
    "symbol": "Cl",
    "number": 17,
    "aMass": 35.4515,
    "amassunc": "(55)",
    "eConfig": "1s2 2s2 2p6 3s2 3p5",
    "density": "3.214",
    "meltingPoint": "171.65",
    "boilingPoint": "239.11",
    "oxidationStates": "±1,3,5,7",
    "electronegativityPauling": "3.16",
    "electronegativityTandO": "3.5",
    "firstIonizationEnergy": "12.968",
    "valenceAtomicRadiusRDK": "73.66",
    "valenceAtomicRadiusClement": "79",
    "R001AtomicRadius": "206",
    "vanderWallRadius": "182",
    "metallicRadius": "N/A",
    "covalentRadius": "102",
    "valenceEffectiveNuclearChargeRDK": "6.46",
    "valenceEffectiveNuclearChargeGuerra": "6.781",
    "electricalConductivity": "1.0×10⁻²",
    "thermalConductivity": "0.0089",
    "crystallineStructure": "assets/BO.png",
  },
  {
    "name": "Argon",
    "symbol": "Ar",
    "number": 18,
    "aMass": 39.8775,
    "amassunc": "(855)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6",
    "density": "1.7837",
    "meltingPoint": "83.8",
    "boilingPoint": "87.3",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "3.57",
    "firstIonizationEnergy": "15.76",
    "valenceAtomicRadiusRDK": "66.25",
    "valenceAtomicRadiusClement": "71",
    "R001AtomicRadius": "197",
    "vanderWallRadius": "183",
    "metallicRadius": "N/A",
    "covalentRadius": "106",
    "valenceEffectiveNuclearChargeRDK": "7.19",
    "valenceEffectiveNuclearChargeGuerra": "7.502",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.01772",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Potassium",
    "symbol": "K",
    "number": 19,
    "aMass": 39.0983,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 4s1",
    "density": "0.89",
    "meltingPoint": "336.53",
    "boilingPoint": "1032",
    "oxidationStates": "1",
    "electronegativityPauling": "0.82",
    "electronegativityTandO": "2.07",
    "firstIonizationEnergy": "4.341",
    "valenceAtomicRadiusRDK": "289.08",
    "valenceAtomicRadiusClement": "243",
    "R001AtomicRadius": "234",
    "vanderWallRadius": "273",
    "metallicRadius": "227",
    "covalentRadius": "203",
    "valenceEffectiveNuclearChargeRDK": "2.93",
    "valenceEffectiveNuclearChargeGuerra": "4.593",
    "electricalConductivity": "1.4×10⁷",
    "thermalConductivity": "100",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Calcium",
    "symbol": "Ca",
    "number": 20,
    "aMass": 40.078,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 4s2",
    "density": "1.54",
    "meltingPoint": "1115",
    "boilingPoint": "1757",
    "oxidationStates": "2",
    "electronegativityPauling": "1",
    "electronegativityTandO": "2.2",
    "firstIonizationEnergy": "6.113",
    "valenceAtomicRadiusRDK": "213.51",
    "valenceAtomicRadiusClement": "194",
    "R001AtomicRadius": "270",
    "vanderWallRadius": "262",
    "metallicRadius": "197",
    "covalentRadius": "176",
    "valenceEffectiveNuclearChargeRDK": "3.96",
    "valenceEffectiveNuclearChargeGuerra": "5.709",
    "electricalConductivity": "2.9×10⁷",
    "thermalConductivity": "200",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Scandium",
    "symbol": "Sc",
    "number": 21,
    "aMass": 44.955907,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d1 4s2",
    "density": "2.99",
    "meltingPoint": "1814",
    "boilingPoint": "3109",
    "oxidationStates": "3",
    "electronegativityPauling": "1.36",
    "electronegativityTandO": "2.35",
    "firstIonizationEnergy": "6.561",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "184",
    "R001AtomicRadius": "263",
    "vanderWallRadius": "258",
    "metallicRadius": "162",
    "covalentRadius": "170",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.09",
    "electricalConductivity": "1.8×10⁶",
    "thermalConductivity": "16",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Titanium",
    "symbol": "Ti",
    "number": 22,
    "aMass": 47.867,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d2 4s2",
    "density": "4.5",
    "meltingPoint": "1941",
    "boilingPoint": "3560",
    "oxidationStates": "4",
    "electronegativityPauling": "1.54",
    "electronegativityTandO": "2.23",
    "firstIonizationEnergy": "6.828",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "176",
    "R001AtomicRadius": "257",
    "vanderWallRadius": "246",
    "metallicRadius": "147",
    "covalentRadius": "160",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.388",
    "electricalConductivity": "2.5×10⁶",
    "thermalConductivity": "22",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Vanadium",
    "symbol": "V",
    "number": 23,
    "aMass": 50.9415,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d3 4s2",
    "density": "6",
    "meltingPoint": "2183",
    "boilingPoint": "3680",
    "oxidationStates": "5",
    "electronegativityPauling": "1.63",
    "electronegativityTandO": "2.08",
    "firstIonizationEnergy": "6.746",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "171",
    "R001AtomicRadius": "252",
    "vanderWallRadius": "242",
    "metallicRadius": "134",
    "covalentRadius": "153",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.664",
    "electricalConductivity": "5.0×10⁶",
    "thermalConductivity": "31",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Chromium",
    "symbol": "Cr",
    "number": 24,
    "aMass": 51.9961,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d5 4s1",
    "density": "7.15",
    "meltingPoint": "2180",
    "boilingPoint": "2944",
    "oxidationStates": "3,6",
    "electronegativityPauling": "1.66",
    "electronegativityTandO": "2.12",
    "firstIonizationEnergy": "6.767",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "166",
    "R001AtomicRadius": "233",
    "vanderWallRadius": "245",
    "metallicRadius": "128",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.615",
    "electricalConductivity": "7.9×10⁶",
    "thermalConductivity": "94",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Manganese",
    "symbol": "Mn",
    "number": 25,
    "aMass": 54.938043,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d5 4s2",
    "density": "7.3",
    "meltingPoint": "1519",
    "boilingPoint": "2334",
    "oxidationStates": "2,4,7",
    "electronegativityPauling": "1.55",
    "electronegativityTandO": "2.2",
    "firstIonizationEnergy": "7.434",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "161",
    "R001AtomicRadius": "242",
    "vanderWallRadius": "245",
    "metallicRadius": "127",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "7.161",
    "electricalConductivity": "6.2×10⁵",
    "thermalConductivity": "7.7",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Iron",
    "symbol": "Fe",
    "number": 26,
    "aMass": 55.845,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d6 4s2",
    "density": "7.874",
    "meltingPoint": "1811",
    "boilingPoint": "3134",
    "oxidationStates": "2,3",
    "electronegativityPauling": "1.83",
    "electronegativityTandO": "2.31",
    "firstIonizationEnergy": "7.902",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "156",
    "R001AtomicRadius": "226",
    "vanderWallRadius": "244",
    "metallicRadius": "126",
    "covalentRadius": "132",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "7.442",
    "electricalConductivity": "1.0×10⁷",
    "thermalConductivity": "79",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Cobalt",
    "symbol": "Co",
    "number": 27,
    "aMass": 58.933194,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d7 4s2",
    "density": "8.86",
    "meltingPoint": "1768",
    "boilingPoint": "3200",
    "oxidationStates": "2,3",
    "electronegativityPauling": "1.88",
    "electronegativityTandO": "2.34",
    "firstIonizationEnergy": "7.881",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "152",
    "R001AtomicRadius": "222",
    "vanderWallRadius": "240",
    "metallicRadius": "125",
    "covalentRadius": "126",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "7.699",
    "electricalConductivity": "1.7×10⁷",
    "thermalConductivity": "100",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Nickel",
    "symbol": "Ni",
    "number": 28,
    "aMass": 58.6934,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d8 4s2",
    "density": "8.912",
    "meltingPoint": "1728",
    "boilingPoint": "3186",
    "oxidationStates": "2",
    "electronegativityPauling": "1.91",
    "electronegativityTandO": "2.32",
    "firstIonizationEnergy": "7.64",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "149",
    "R001AtomicRadius": "219",
    "vanderWallRadius": "240",
    "metallicRadius": "124",
    "covalentRadius": "124",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "7.948",
    "electricalConductivity": "1.4×10⁷",
    "thermalConductivity": "91",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Copper",
    "symbol": "Cu",
    "number": 29,
    "aMass": 63.546,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s1",
    "density": "8.933",
    "meltingPoint": "1357.77",
    "boilingPoint": "2835",
    "oxidationStates": "2",
    "electronegativityPauling": "1.9",
    "electronegativityTandO": "2.86",
    "firstIonizationEnergy": "7.726",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "145",
    "R001AtomicRadius": "217",
    "vanderWallRadius": "238",
    "metallicRadius": "128",
    "covalentRadius": "132",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "7.351",
    "electricalConductivity": "5.9×10⁷",
    "thermalConductivity": "400",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Zinc",
    "symbol": "Zn",
    "number": 30,
    "aMass": 65.38,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2",
    "density": "7.134",
    "meltingPoint": "692.68",
    "boilingPoint": "1180",
    "oxidationStates": "2",
    "electronegativityPauling": "1.65",
    "electronegativityTandO": "2.26",
    "firstIonizationEnergy": "9.394",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "142",
    "R001AtomicRadius": "222",
    "vanderWallRadius": "239",
    "metallicRadius": "134",
    "covalentRadius": "122",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "8.416",
    "electricalConductivity": "1.7×10⁷",
    "thermalConductivity": "120",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Gallium",
    "symbol": "Ga",
    "number": 31,
    "aMass": 69.723,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1",
    "density": "5.91",
    "meltingPoint": "302.91",
    "boilingPoint": "2477",
    "oxidationStates": "3",
    "electronegativityPauling": "1.81",
    "electronegativityTandO": "2.43",
    "firstIonizationEnergy": "5.999",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "136",
    "R001AtomicRadius": "233",
    "vanderWallRadius": "232",
    "metallicRadius": "135",
    "covalentRadius": "122",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.779",
    "electricalConductivity": "7.1×10⁶",
    "thermalConductivity": "29",
    "crystallineStructure": "assets/BO.png",
  },
  {
    "name": "Germanium",
    "symbol": "Ge",
    "number": 32,
    "aMass": 72.630,
    "amassunc": "(8)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2",
    "density": "5.323",
    "meltingPoint": "1211.4",
    "boilingPoint": "3106",
    "oxidationStates": "±4,2",
    "electronegativityPauling": "2.01",
    "electronegativityTandO": "2.79",
    "firstIonizationEnergy": "7.9",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "125",
    "R001AtomicRadius": "234",
    "vanderWallRadius": "229",
    "metallicRadius": "N/A",
    "covalentRadius": "120",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "8.052",
    "electricalConductivity": "2.0×10³",
    "thermalConductivity": "60",
    "crystallineStructure": "assets/Diamond.png",
  },
  {
    "name": "Arsenic",
    "symbol": "As",
    "number": 33,
    "aMass": 74.921595,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3",
    "density": "5.776",
    "meltingPoint": "1090",
    "boilingPoint": "887",
    "oxidationStates": "±3,5",
    "electronegativityPauling": "2.18",
    "electronegativityTandO": "3.15",
    "firstIonizationEnergy": "9.815",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "114",
    "R001AtomicRadius": "231",
    "vanderWallRadius": "188",
    "metallicRadius": "N/A",
    "covalentRadius": "119",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "9.137",
    "electricalConductivity": "3.3×10⁶",
    "thermalConductivity": "50",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Selenium",
    "symbol": "Se",
    "number": 34,
    "aMass": 78.971,
    "amassunc": "(8)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4",
    "density": "4.809",
    "meltingPoint": "493.65",
    "boilingPoint": "958",
    "oxidationStates": "±2,4,6",
    "electronegativityPauling": "2.55",
    "electronegativityTandO": "3.37",
    "firstIonizationEnergy": "9.752",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "103",
    "R001AtomicRadius": "214",
    "vanderWallRadius": "182",
    "metallicRadius": "N/A",
    "covalentRadius": "120",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.52",
    "crystallineStructure": "assets/SM.png",
  },
  {
    "name": "Bromine",
    "symbol": "Br",
    "number": 35,
    "aMass": 79.904,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5",
    "density": "3.11",
    "meltingPoint": "265.95",
    "boilingPoint": "331.95",
    "oxidationStates": "±1,3,5",
    "electronegativityPauling": "2.96",
    "electronegativityTandO": "3.45",
    "firstIonizationEnergy": "11.814",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "94",
    "R001AtomicRadius": "219",
    "vanderWallRadius": "186",
    "metallicRadius": "N/A",
    "covalentRadius": "120",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.849",
    "electricalConductivity": "1.0×10⁻¹⁰",
    "thermalConductivity": "0.12",
    "crystallineStructure": "assets/BO.png",
  },
  {
    "name": "Krypton",
    "symbol": "Kr",
    "number": 36,
    "aMass": 83.798,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6",
    "density": "3.733",
    "meltingPoint": "115.79",
    "boilingPoint": "119.93",
    "oxidationStates": "2",
    "electronegativityPauling": "3",
    "electronegativityTandO": "3.37",
    "firstIonizationEnergy": "14",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "88",
    "R001AtomicRadius": "212",
    "vanderWallRadius": "225",
    "metallicRadius": "N/A",
    "covalentRadius": "116",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.731",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.00943",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Rubidium",
    "symbol": "Rb",
    "number": 37,
    "aMass": 85.4678,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1",
    "density": "1.53",
    "meltingPoint": "312.46",
    "boilingPoint": "961",
    "oxidationStates": "1",
    "electronegativityPauling": "0.82",
    "electronegativityTandO": "2.07",
    "firstIonizationEnergy": "4.177",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "265",
    "R001AtomicRadius": "240",
    "vanderWallRadius": "321",
    "metallicRadius": "248",
    "covalentRadius": "220",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "6.76",
    "electricalConductivity": "8.3×10⁶",
    "thermalConductivity": "58",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Strontium",
    "symbol": "Sr",
    "number": 38,
    "aMass": 87.62,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2",
    "density": "2.64",
    "meltingPoint": "1050",
    "boilingPoint": "1655",
    "oxidationStates": "2",
    "electronegativityPauling": "0.95",
    "electronegativityTandO": "2.13",
    "firstIonizationEnergy": "5.695",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "219",
    "R001AtomicRadius": "279",
    "vanderWallRadius": "284",
    "metallicRadius": "215",
    "covalentRadius": "195",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "8.21",
    "electricalConductivity": "7.7×10⁶",
    "thermalConductivity": "35",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Yttrium",
    "symbol": "Y",
    "number": 39,
    "aMass": 88.905838,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2",
    "density": "4.47",
    "meltingPoint": "1795",
    "boilingPoint": "3618",
    "oxidationStates": "3",
    "electronegativityPauling": "1.22",
    "electronegativityTandO": "2.52",
    "firstIonizationEnergy": "6.217",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "212",
    "R001AtomicRadius": "274",
    "vanderWallRadius": "275",
    "metallicRadius": "180",
    "covalentRadius": "190",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "8.401",
    "electricalConductivity": "1.8×10⁶",
    "thermalConductivity": "17",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Zirconium",
    "symbol": "Zr",
    "number": 40,
    "aMass": 91.222,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2",
    "density": "6.52",
    "meltingPoint": "2128",
    "boilingPoint": "4682",
    "oxidationStates": "4",
    "electronegativityPauling": "1.33",
    "electronegativityTandO": "2.05",
    "firstIonizationEnergy": "6.634",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "206",
    "R001AtomicRadius": "268",
    "vanderWallRadius": "252",
    "metallicRadius": "160",
    "covalentRadius": "175",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "9.372",
    "electricalConductivity": "2.4×10⁶",
    "thermalConductivity": "23",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Niobium",
    "symbol": "Nb",
    "number": 41,
    "aMass": 92.90637,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1",
    "density": "8.57",
    "meltingPoint": "2750",
    "boilingPoint": "5017",
    "oxidationStates": "5",
    "electronegativityPauling": "1.6",
    "electronegativityTandO": "2.59",
    "firstIonizationEnergy": "6.759",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "198",
    "R001AtomicRadius": "251",
    "vanderWallRadius": "256",
    "metallicRadius": "146",
    "covalentRadius": "164",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "9.751",
    "electricalConductivity": "6.7×10⁶",
    "thermalConductivity": "54",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Molybdenum",
    "symbol": "Mo",
    "number": 42,
    "aMass": 95.95,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1",
    "density": "10.2",
    "meltingPoint": "2896",
    "boilingPoint": "4912",
    "oxidationStates": "4,6",
    "electronegativityPauling": "2.16",
    "electronegativityTandO": "2.47",
    "firstIonizationEnergy": "7.092",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "190",
    "R001AtomicRadius": "244",
    "vanderWallRadius": "245",
    "metallicRadius": "139",
    "covalentRadius": "154",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.162",
    "electricalConductivity": "2.0×10⁷",
    "thermalConductivity": "139",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Technetium",
    "symbol": "Tc",
    "number": 43,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2",
    "density": "11",
    "meltingPoint": "2430",
    "boilingPoint": "4538",
    "oxidationStates": "4,7",
    "electronegativityPauling": "1.9",
    "electronegativityTandO": "2.82",
    "firstIonizationEnergy": "7.28",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "183",
    "R001AtomicRadius": "241",
    "vanderWallRadius": "244",
    "metallicRadius": "136",
    "covalentRadius": "147",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.498",
    "electricalConductivity": "5.0×10⁶",
    "thermalConductivity": "51",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Ruthenium",
    "symbol": "Ru",
    "number": 44,
    "aMass": 101.07,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s",
    "density": "12.1",
    "meltingPoint": "2607",
    "boilingPoint": "4423",
    "oxidationStates": "3,4",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "2.68",
    "firstIonizationEnergy": "7.361",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "178",
    "R001AtomicRadius": "237",
    "vanderWallRadius": "246",
    "metallicRadius": "134",
    "covalentRadius": "146",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.518",
    "electricalConductivity": "1.4×10⁷",
    "thermalConductivity": "120",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Rhodium",
    "symbol": "Rh",
    "number": 45,
    "aMass": 102.90549,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s2",
    "density": "12.4",
    "meltingPoint": "2237",
    "boilingPoint": "3968",
    "oxidationStates": "3",
    "electronegativityPauling": "2.28",
    "electronegativityTandO": "2.65",
    "firstIonizationEnergy": "7.459",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "173",
    "R001AtomicRadius": "233",
    "vanderWallRadius": "244",
    "metallicRadius": "134",
    "covalentRadius": "142",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.649",
    "electricalConductivity": "2.3×10⁷",
    "thermalConductivity": "150",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Palladium",
    "symbol": "Pd",
    "number": 46,
    "aMass": 106.42,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10",
    "density": "12",
    "meltingPoint": "1828.05",
    "boilingPoint": "3236",
    "oxidationStates": "2,4",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "2.7",
    "firstIonizationEnergy": "8.337",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "169",
    "R001AtomicRadius": "215",
    "vanderWallRadius": "215",
    "metallicRadius": "137",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "13.417",
    "electricalConductivity": "1.0×10⁷",
    "thermalConductivity": "71",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Silver",
    "symbol": "Ag",
    "number": 47,
    "aMass": 107.8682,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1",
    "density": "10.501",
    "meltingPoint": "1234.93",
    "boilingPoint": "2435",
    "oxidationStates": "1",
    "electronegativityPauling": "1.93",
    "electronegativityTandO": "2.88",
    "firstIonizationEnergy": "7.576",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "165",
    "R001AtomicRadius": "225",
    "vanderWallRadius": "253",
    "metallicRadius": "144",
    "covalentRadius": "145",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.848",
    "electricalConductivity": "6.2×10⁷",
    "thermalConductivity": "430",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Cadmium",
    "symbol": "Cd",
    "number": 48,
    "aMass": 112.414,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2",
    "density": "8.69",
    "meltingPoint": "594.22",
    "boilingPoint": "1040",
    "oxidationStates": "2",
    "electronegativityPauling": "1.69",
    "electronegativityTandO": "2.36",
    "firstIonizationEnergy": "8.994",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "161",
    "R001AtomicRadius": "238",
    "vanderWallRadius": "249",
    "metallicRadius": "151",
    "covalentRadius": "144",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.118",
    "electricalConductivity": "1.4×10⁷",
    "thermalConductivity": "96",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Indium",
    "symbol": "In",
    "number": 49,
    "aMass": 114.818,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1",
    "density": "7.31",
    "meltingPoint": "429.75",
    "boilingPoint": "2345",
    "oxidationStates": "3",
    "electronegativityPauling": "1.78",
    "electronegativityTandO": "2.29",
    "firstIonizationEnergy": "5.786",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "156",
    "R001AtomicRadius": "246",
    "vanderWallRadius": "242",
    "metallicRadius": "167",
    "covalentRadius": "142",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "9.943",
    "electricalConductivity": "1.2×10⁷",
    "thermalConductivity": "82",
    "crystallineStructure": "assets/CT.png",
  },
  {
    "name": "Tin",
    "symbol": "Sn",
    "number": 50,
    "aMass": 118.710,
    "amassunc": "(7)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2",
    "density": "7.287",
    "meltingPoint": "505.08",
    "boilingPoint": "2875",
    "oxidationStates": "±4,2",
    "electronegativityPauling": "1.96",
    "electronegativityTandO": "2.68",
    "firstIonizationEnergy": "7.344",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "145",
    "R001AtomicRadius": "248",
    "vanderWallRadius": "242",
    "metallicRadius": "N/A",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.382",
    "electricalConductivity": "9.1×10⁶",
    "thermalConductivity": "67",
    "crystallineStructure": "assets/CT.png",
  },
  {
    "name": "Antimony",
    "symbol": "Sb",
    "number": 51,
    "aMass": 121.760,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p3",
    "density": "6.685",
    "meltingPoint": "903.78",
    "boilingPoint": "1860",
    "oxidationStates": "±3,5",
    "electronegativityPauling": "2.05",
    "electronegativityTandO": "3.05",
    "firstIonizationEnergy": "8.64",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "133",
    "R001AtomicRadius": "246",
    "vanderWallRadius": "247",
    "metallicRadius": "N/A",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.549",
    "electricalConductivity": "2.5×10⁶",
    "thermalConductivity": "24 ",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Tellerium",
    "symbol": "Te",
    "number": 52,
    "aMass": 127.60,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p4",
    "density": "6.232",
    "meltingPoint": "722.66",
    "boilingPoint": "1261",
    "oxidationStates": "±2,4,6",
    "electronegativityPauling": "2.1",
    "electronegativityTandO": "3.14",
    "firstIonizationEnergy": "9.01",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "123",
    "R001AtomicRadius": "242",
    "vanderWallRadius": "199",
    "metallicRadius": "N/A",
    "covalentRadius": "138",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "13.503",
    "electricalConductivity": "1.0×10⁴",
    "thermalConductivity": "3",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Iodine",
    "symbol": "I",
    "number": 53,
    "aMass": 126.90447,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p5",
    "density": "4.93",
    "meltingPoint": "386.85",
    "boilingPoint": "457.55",
    "oxidationStates": "±1,3,5,7",
    "electronegativityPauling": "2.66",
    "electronegativityTandO": "3.2",
    "firstIonizationEnergy": "10.451",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "115",
    "R001AtomicRadius": "238",
    "vanderWallRadius": "204",
    "metallicRadius": "N/A",
    "covalentRadius": "139",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "14.478",
    "electricalConductivity": "1.0×10⁻⁷",
    "thermalConductivity": "0.449",
    "crystallineStructure": "assets/BO.png",
  },
  {
    "name": "Xenon",
    "symbol": "Xe",
    "number": 54,
    "aMass": 131.293,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6",
    "density": "5.887",
    "meltingPoint": "161.36",
    "boilingPoint": "165.03",
    "oxidationStates": "2,4,6",
    "electronegativityPauling": "2.6",
    "electronegativityTandO": "3.12",
    "firstIonizationEnergy": "12.13",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "108",
    "R001AtomicRadius": "232",
    "vanderWallRadius": "206",
    "metallicRadius": "N/A",
    "covalentRadius": "140",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "15.498",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.00565",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Caesium",
    "symbol": "Cs",
    "number": 55,
    "aMass": 132.90545196,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s1",
    "density": "1.93",
    "meltingPoint": "301.59",
    "boilingPoint": "944",
    "oxidationStates": "1",
    "electronegativityPauling": "0.79",
    "electronegativityTandO": "1.97",
    "firstIonizationEnergy": "3.894",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "298",
    "R001AtomicRadius": "249",
    "vanderWallRadius": "348",
    "metallicRadius": "265",
    "covalentRadius": "244",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "8.869",
    "electricalConductivity": "5.0×10⁶",
    "thermalConductivity": "36",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Barium",
    "symbol": "Ba",
    "number": 56,
    "aMass": 137.327,
    "amassunc": "(7)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s2",
    "density": "3.62",
    "meltingPoint": "1000",
    "boilingPoint": "2170",
    "oxidationStates": "2",
    "electronegativityPauling": "0.89",
    "electronegativityTandO": "2.02",
    "firstIonizationEnergy": "5.212",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "253",
    "R001AtomicRadius": "293",
    "vanderWallRadius": "303",
    "metallicRadius": "222",
    "covalentRadius": "215",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "10.612",
    "electricalConductivity": "2.9×10⁶",
    "thermalConductivity": "18",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Lanthanum",
    "symbol": "La",
    "number": 57,
    "aMass": 138.90547,
    "amassunc": "(7)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 5d1 6s2",
    "density": "6.15",
    "meltingPoint": "1191",
    "boilingPoint": "3737",
    "oxidationStates": "3",
    "electronegativityPauling": "1.1",
    "electronegativityTandO": "2.49",
    "firstIonizationEnergy": "5.577",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "622",
    "R001AtomicRadius": "284",
    "vanderWallRadius": "298",
    "metallicRadius": "187",
    "covalentRadius": "207",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.407",
    "electricalConductivity": "1.6×10⁶",
    "thermalConductivity": "13",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Cerium",
    "symbol": "Ce",
    "number": 58,
    "aMass": 140.116,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f1 5d1 6s2",
    "density": "6.77",
    "meltingPoint": "1071",
    "boilingPoint": "3697",
    "oxidationStates": "3,4",
    "electronegativityPauling": "1.12",
    "electronegativityTandO": "2.62",
    "firstIonizationEnergy": "5.539",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "505",
    "R001AtomicRadius": "282",
    "vanderWallRadius": "288",
    "metallicRadius": "181.8",
    "covalentRadius": "204",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.539",
    "electricalConductivity": "1.4×10⁶",
    "thermalConductivity": "11",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Preseodymium",
    "symbol": "Pr",
    "number": 59,
    "aMass": 140.90766,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f3 6s2",
    "density": "6.77",
    "meltingPoint": "1204",
    "boilingPoint": "3793",
    "oxidationStates": "3",
    "electronegativityPauling": "1.13",
    "electronegativityTandO": "2.24",
    "firstIonizationEnergy": "5.464",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "247",
    "R001AtomicRadius": "286",
    "vanderWallRadius": "292",
    "metallicRadius": "182.4",
    "covalentRadius": "203",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.134",
    "electricalConductivity": "1.4×10⁶",
    "thermalConductivity": "13",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Neodymium",
    "symbol": "Nd",
    "number": 60,
    "aMass": 144.242,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f4 6s2",
    "density": "7.01",
    "meltingPoint": "1294",
    "boilingPoint": "3347",
    "oxidationStates": "3",
    "electronegativityPauling": "1.14",
    "electronegativityTandO": "2.11",
    "firstIonizationEnergy": "5.525",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "206",
    "R001AtomicRadius": "284",
    "vanderWallRadius": "295",
    "metallicRadius": "181.4",
    "covalentRadius": "201",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.285",
    "electricalConductivity": "1.6×10⁶",
    "thermalConductivity": "17",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Promethium",
    "symbol": "Pm",
    "number": 61,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f5 6s2",
    "density": "7.26",
    "meltingPoint": "1315",
    "boilingPoint": "3273",
    "oxidationStates": "3",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.24",
    "firstIonizationEnergy": "5.55",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "205",
    "R001AtomicRadius": "283",
    "vanderWallRadius": "N/A",
    "metallicRadius": "183.4",
    "covalentRadius": "199",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.434",
    "electricalConductivity": "1.3×10⁶",
    "thermalConductivity": "15",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Samarium",
    "symbol": "Sm",
    "number": 62,
    "aMass": 150.36,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f6 6s2",
    "density": "7.52",
    "meltingPoint": "1347",
    "boilingPoint": "2067",
    "oxidationStates": "3",
    "electronegativityPauling": "1.17",
    "electronegativityTandO": "1.9",
    "firstIonizationEnergy": "5.644",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "238",
    "R001AtomicRadius": "280",
    "vanderWallRadius": "290",
    "metallicRadius": "180.4",
    "covalentRadius": "198",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.577",
    "electricalConductivity": "1.1×10⁶",
    "thermalConductivity": "13",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Europium",
    "symbol": "Eu",
    "number": 63,
    "aMass": 151.964,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f7 6s2",
    "density": "5.24",
    "meltingPoint": "1095",
    "boilingPoint": "1802",
    "oxidationStates": "2,3",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "1.81",
    "firstIonizationEnergy": "5.67",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "231",
    "R001AtomicRadius": "280",
    "vanderWallRadius": "287",
    "metallicRadius": "180.4",
    "covalentRadius": "198",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "11.714",
    "electricalConductivity": "1.1×10⁶",
    "thermalConductivity": "14",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Gadolinium",
    "symbol": "Gd",
    "number": 64,
    "aMass": 157.249,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f7 5d1 6s2",
    "density": "7.9",
    "meltingPoint": "1586",
    "boilingPoint": "3546",
    "oxidationStates": "3",
    "electronegativityPauling": "1.2",
    "electronegativityTandO": "2.4",
    "firstIonizationEnergy": "6.15",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "233",
    "R001AtomicRadius": "277",
    "vanderWallRadius": "283",
    "metallicRadius": "180.4",
    "covalentRadius": "196",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.493",
    "electricalConductivity": "7.7×10⁵",
    "thermalConductivity": "11",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Terbium",
    "symbol": "Tb",
    "number": 65,
    "aMass": 158.925354,
    "amassunc": "(7)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f9 6s2",
    "density": "8.23",
    "meltingPoint": "1629",
    "boilingPoint": "3503",
    "oxidationStates": "3",
    "electronegativityPauling": "1.1",
    "electronegativityTandO": "2.29",
    "firstIonizationEnergy": "5.864",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "225",
    "R001AtomicRadius": "276",
    "vanderWallRadius": "279",
    "metallicRadius": "177.3",
    "covalentRadius": "194",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.019",
    "electricalConductivity": "8.3×10⁵",
    "thermalConductivity": "11",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Dysprosium",
    "symbol": "Dy",
    "number": 66,
    "aMass": 162.500,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f10 6s2",
    "density": "8.55",
    "meltingPoint": "1685",
    "boilingPoint": "2840",
    "oxidationStates": "3",
    "electronegativityPauling": "1.22",
    "electronegativityTandO": "2.07",
    "firstIonizationEnergy": "5.939",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "228",
    "R001AtomicRadius": "275",
    "vanderWallRadius": "287",
    "metallicRadius": "178.1",
    "covalentRadius": "192",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.164",
    "electricalConductivity": "1.1×10⁶",
    "thermalConductivity": "11",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Holmium",
    "symbol": "Ho",
    "number": 67,
    "aMass": 164.930329,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f11 6s2",
    "density": "8.8",
    "meltingPoint": "1747",
    "boilingPoint": "2973",
    "oxidationStates": "3",
    "electronegativityPauling": "1.23",
    "electronegativityTandO": "2.12",
    "firstIonizationEnergy": "6.022",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "226",
    "R001AtomicRadius": "273",
    "vanderWallRadius": "281",
    "metallicRadius": "176.2",
    "covalentRadius": "192",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.31",
    "electricalConductivity": "1.1×10⁶",
    "thermalConductivity": "16",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Erbium",
    "symbol": "Er",
    "number": 68,
    "aMass": 167.259,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f12 6s2",
    "density": "9.07",
    "meltingPoint": "1802",
    "boilingPoint": "3141",
    "oxidationStates": "3",
    "electronegativityPauling": "1.24",
    "electronegativityTandO": "2.02",
    "firstIonizationEnergy": "6.108",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "226",
    "R001AtomicRadius": "272",
    "vanderWallRadius": "283",
    "metallicRadius": "176.1",
    "covalentRadius": "189",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.457",
    "electricalConductivity": "1.2×10⁶",
    "thermalConductivity": "15",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Thulium",
    "symbol": "Tm",
    "number": 69,
    "aMass": 168.934219,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f13 6s2",
    "density": "9.32",
    "meltingPoint": "1818",
    "boilingPoint": "2223",
    "oxidationStates": "3",
    "electronegativityPauling": "1.25",
    "electronegativityTandO": "2.03",
    "firstIonizationEnergy": "6.184",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "222",
    "R001AtomicRadius": "271",
    "vanderWallRadius": "279",
    "metallicRadius": "175.9",
    "covalentRadius": "190",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.601",
    "electricalConductivity": "1.4×10⁶",
    "thermalConductivity": "17",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Ytterbium",
    "symbol": "Yb",
    "number": 70,
    "aMass": 173.045,
    "amassunc": "(10)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 6s2",
    "density": "6.9",
    "meltingPoint": "1092",
    "boilingPoint": "1469",
    "oxidationStates": "3",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "1.78",
    "firstIonizationEnergy": "6.254",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "222",
    "R001AtomicRadius": "277",
    "vanderWallRadius": "280",
    "metallicRadius": "176",
    "covalentRadius": "187",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.741",
    "electricalConductivity": "3.6×10⁶",
    "thermalConductivity": "39",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Lutetium",
    "symbol": "Lu",
    "number": 71,
    "aMass": 174.96669,
    "amassunc": "(5)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d1 6s2",
    "density": "9.84",
    "meltingPoint": "1936",
    "boilingPoint": "3675",
    "oxidationStates": "3",
    "electronegativityPauling": "1.27",
    "electronegativityTandO": "2.68",
    "firstIonizationEnergy": "5.426",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "217",
    "R001AtomicRadius": "270",
    "vanderWallRadius": "274",
    "metallicRadius": "173.8",
    "covalentRadius": "187",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.841",
    "electricalConductivity": "1.8×10⁶",
    "thermalConductivity": "16",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Hafnium",
    "symbol": "Hf",
    "number": 72,
    "aMass": 178.486,
    "amassunc": "(6)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d2 6s2",
    "density": "13.3",
    "meltingPoint": "2506",
    "boilingPoint": "4876",
    "oxidationStates": "4",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.01",
    "firstIonizationEnergy": "6.825",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "208",
    "R001AtomicRadius": "264",
    "vanderWallRadius": "263",
    "metallicRadius": "159",
    "covalentRadius": "175",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "14.473",
    "electricalConductivity": "3.3×10⁶",
    "thermalConductivity": "23",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Tantalum",
    "symbol": "Ta",
    "number": 73,
    "aMass": 180.94788,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d3 6s2",
    "density": "16.4",
    "meltingPoint": "3290",
    "boilingPoint": "5731",
    "oxidationStates": "5",
    "electronegativityPauling": "1.5",
    "electronegativityTandO": "2.32",
    "firstIonizationEnergy": "7.89",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "200",
    "R001AtomicRadius": "258",
    "vanderWallRadius": "253",
    "metallicRadius": "146",
    "covalentRadius": "170",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "15.109",
    "electricalConductivity": "7.7×10⁶",
    "thermalConductivity": "57",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Tungsten",
    "symbol": "W",
    "number": 74,
    "aMass": 183.84,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d4 6s2",
    "density": "19.3",
    "meltingPoint": "3695",
    "boilingPoint": "5828",
    "oxidationStates": "4,6",
    "electronegativityPauling": "2.36",
    "electronegativityTandO": "2.42",
    "firstIonizationEnergy": "7.98",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "193",
    "R001AtomicRadius": "253",
    "vanderWallRadius": "257",
    "metallicRadius": "139",
    "covalentRadius": "162",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "15.691",
    "electricalConductivity": "2.0×10⁷",
    "thermalConductivity": "170",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Rhenium",
    "symbol": "Re",
    "number": 75,
    "aMass": 186.207,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d5 6s2",
    "density": "20.8",
    "meltingPoint": "3459",
    "boilingPoint": "5869",
    "oxidationStates": "4",
    "electronegativityPauling": "1.9",
    "electronegativityTandO": "2.59",
    "firstIonizationEnergy": "7.88",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "188",
    "R001AtomicRadius": "249",
    "vanderWallRadius": "249",
    "metallicRadius": "137",
    "covalentRadius": "151",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.244",
    "electricalConductivity": "5.6×10⁶",
    "thermalConductivity": "48",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Osmium",
    "symbol": "Os",
    "number": 76,
    "aMass": 190.23,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2",
    "density": "22.57",
    "meltingPoint": "3306",
    "boilingPoint": "5285",
    "oxidationStates": "4",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "2.72",
    "firstIonizationEnergy": "8.7",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "185",
    "R001AtomicRadius": "244",
    "vanderWallRadius": "248",
    "metallicRadius": "135",
    "covalentRadius": "144",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.843",
    "electricalConductivity": "1.2×10⁷",
    "thermalConductivity": "87",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Iridium",
    "symbol": "Ir",
    "number": 77,
    "aMass": 192.217,
    "amassunc": "(2)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d7 6s2",
    "density": "22.42",
    "meltingPoint": "2719",
    "boilingPoint": "4701",
    "oxidationStates": "3,4",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "2.79",
    "firstIonizationEnergy": "9.1",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "180",
    "R001AtomicRadius": "233",
    "vanderWallRadius": "241",
    "metallicRadius": "135.5",
    "covalentRadius": "141",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.391",
    "electricalConductivity": "2.1×10⁷",
    "thermalConductivity": "150",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Platinum",
    "symbol": "Pt",
    "number": 78,
    "aMass": 195.084,
    "amassunc": "(9)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d9 6s",
    "density": "21.46",
    "meltingPoint": "2041.55",
    "boilingPoint": "4098",
    "oxidationStates": "2,4",
    "electronegativityPauling": "2.28",
    "electronegativityTandO": "2.98",
    "firstIonizationEnergy": "9",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "177",
    "R001AtomicRadius": "230",
    "vanderWallRadius": "229",
    "metallicRadius": "138.5",
    "covalentRadius": "136",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.381",
    "electricalConductivity": "9.4×10⁶",
    "thermalConductivity": "71",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Gold",
    "symbol": "Au",
    "number": 79,
    "aMass": 196.966570,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2",
    "density": "19.282",
    "meltingPoint": "1337.33",
    "boilingPoint": "3129",
    "oxidationStates": "3",
    "electronegativityPauling": "2.54",
    "electronegativityTandO": "2.81",
    "firstIonizationEnergy": "9.226",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "174",
    "R001AtomicRadius": "226",
    "vanderWallRadius": "232",
    "metallicRadius": "144",
    "covalentRadius": "136",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.586",
    "electricalConductivity": "4.5×10⁷",
    "thermalConductivity": "320",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Mercury",
    "symbol": "Hg",
    "number": 80,
    "aMass": 200.592,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2",
    "density": "13.5336",
    "meltingPoint": "234.32",
    "boilingPoint": "629.88",
    "oxidationStates": "1,2",
    "electronegativityPauling": "2",
    "electronegativityTandO": "2.92",
    "firstIonizationEnergy": "10.438",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "171",
    "R001AtomicRadius": "229",
    "vanderWallRadius": "254",
    "metallicRadius": "151",
    "covalentRadius": "132",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "18.926",
    "electricalConductivity": "1.0×10⁶",
    "thermalConductivity": "8.3",
    "crystallineStructure": "assets/RHOM.png",
  },
  {
    "name": "Thallium",
    "symbol": "Tl",
    "number": 81,
    "aMass": 204.3835,
    "amassunc": "(15)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p1",
    "density": "11.8",
    "meltingPoint": "577",
    "boilingPoint": "1746",
    "oxidationStates": "1,3",
    "electronegativityPauling": "1.62",
    "electronegativityTandO": "2.26",
    "firstIonizationEnergy": "6.108",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "156",
    "R001AtomicRadius": "242",
    "vanderWallRadius": "247",
    "metallicRadius": "170",
    "covalentRadius": "145",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "15.075",
    "electricalConductivity": "6.7×10⁶",
    "thermalConductivity": "46",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Lead",
    "symbol": "Pb",
    "number": 82,
    "aMass": 207.04,
    "amassunc": "(90)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p2",
    "density": "11.342",
    "meltingPoint": "600.61",
    "boilingPoint": "2022",
    "oxidationStates": "2,4",
    "electronegativityPauling": "1.87",
    "electronegativityTandO": "2.62",
    "firstIonizationEnergy": "7.417",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "154",
    "R001AtomicRadius": "249",
    "vanderWallRadius": "260",
    "metallicRadius": "N/A",
    "covalentRadius": "146",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.455",
    "electricalConductivity": "4.8×10⁶",
    "thermalConductivity": "35",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Bismuth",
    "symbol": "Bi",
    "number": 83,
    "aMass": 208.98040,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p3",
    "density": "9.807",
    "meltingPoint": "544.55",
    "boilingPoint": "1837",
    "oxidationStates": "3",
    "electronegativityPauling": "2.02",
    "electronegativityTandO": "2.69",
    "firstIonizationEnergy": "7.289",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "143",
    "R001AtomicRadius": "250",
    "vanderWallRadius": "254",
    "metallicRadius": "N/A",
    "covalentRadius": "148",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.925",
    "electricalConductivity": "7.7×10⁵",
    "thermalConductivity": "8",
    "crystallineStructure": "assets/BCM.png",
  },
  {
    "name": "Polonium",
    "symbol": "Po",
    "number": 84,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p4",
    "density": "9.32",
    "meltingPoint": "527",
    "boilingPoint": "1235",
    "oxidationStates": "±2,4",
    "electronegativityPauling": "2",
    "electronegativityTandO": "2.85",
    "firstIonizationEnergy": "8.417",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "135",
    "R001AtomicRadius": "250",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "140",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.956",
    "electricalConductivity": "2.3×10⁶",
    "thermalConductivity": "N/A",
    "crystallineStructure": "assets/Cubic.png",
  },
  {
    "name": "Astatine",
    "symbol": "At",
    "number": 85,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p5",
    "density": "7",
    "meltingPoint": "575",
    "boilingPoint": "N/A",
    "oxidationStates": "±1",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "3.04",
    "firstIonizationEnergy": "9.5",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "127",
    "R001AtomicRadius": "247",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "150",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "19.199",
    "electricalConductivity": "N/A",
    "thermalConductivity": "2",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Radon",
    "symbol": "Rn",
    "number": 86,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6",
    "density": "9.73",
    "meltingPoint": "202",
    "boilingPoint": "211.45",
    "oxidationStates": "N/A",
    "electronegativityPauling": "2.2",
    "electronegativityTandO": "3.04",
    "firstIonizationEnergy": "10.745",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "120",
    "R001AtomicRadius": "243",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "150",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "20.478",
    "electricalConductivity": "N/A",
    "thermalConductivity": "0.00361",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Francium",
    "symbol": "Fr",
    "number": 87,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 7s1",
    "density": "N/A",
    "meltingPoint": "300",
    "boilingPoint": "N/A",
    "oxidationStates": "1",
    "electronegativityPauling": "0.79",
    "electronegativityTandO": "2.01",
    "firstIonizationEnergy": "3.9",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "258",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "260",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "12.4",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Radium",
    "symbol": "Ra",
    "number": 88,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 7s2",
    "density": "5",
    "meltingPoint": "973",
    "boilingPoint": "1413",
    "oxidationStates": "2",
    "electronegativityPauling": "0.9",
    "electronegativityTandO": "2.15",
    "firstIonizationEnergy": "5.279",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "292",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "221",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "14.583",
    "electricalConductivity": "1.0×10⁶",
    "thermalConductivity": "19",
    "crystallineStructure": "assets/BCC.jpg",
  },
  {
    "name": "Actinium",
    "symbol": "Ac",
    "number": 89,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 6d1 7s2",
    "density": "10.07",
    "meltingPoint": "1324",
    "boilingPoint": "3471",
    "oxidationStates": "3",
    "electronegativityPauling": "1.1",
    "electronegativityTandO": "2.22",
    "firstIonizationEnergy": "5.17",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "293",
    "vanderWallRadius": "280",
    "metallicRadius": "N/A",
    "covalentRadius": "215",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "14.908",
    "electricalConductivity": "N/A",
    "thermalConductivity": "12",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Thorium",
    "symbol": "Th",
    "number": 90,
    "aMass": 232.0377,
    "amassunc": "(4)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 6d2 7s2",
    "density": "11.72",
    "meltingPoint": "2023",
    "boilingPoint": "5061",
    "oxidationStates": "4",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.62",
    "firstIonizationEnergy": "6.08",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "289",
    "vanderWallRadius": "293",
    "metallicRadius": "179",
    "covalentRadius": "206",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.547",
    "electricalConductivity": "6.7×10⁶",
    "thermalConductivity": "54",
    "crystallineStructure": "assets/FCC.png",
  },
  {
    "name": "Protactinium,",
    "symbol": "Pa",
    "number": 91,
    "aMass": 231.03588,
    "amassunc": "(1)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f3 6d1 7s2",
    "density": "15.37",
    "meltingPoint": "1845",
    "boilingPoint": "N/A",
    "oxidationStates": "5",
    "electronegativityPauling": "1.5",
    "electronegativityTandO": "2.33",
    "firstIonizationEnergy": "5.89",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "285",
    "vanderWallRadius": "288",
    "metallicRadius": "163",
    "covalentRadius": "200",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.414",
    "electricalConductivity": "5.6×10⁶",
    "thermalConductivity": "47",
    "crystallineStructure": "assets/CT.png",
  },
  {
    "name": "Uranium",
    "symbol": "U",
    "number": 92,
    "aMass": 238.02891,
    "amassunc": "(3)",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f3 6d1 7s2",
    "density": "18.95",
    "meltingPoint": "1408",
    "boilingPoint": "4404",
    "oxidationStates": "6",
    "electronegativityPauling": "1.38",
    "electronegativityTandO": "2.45",
    "firstIonizationEnergy": "6.194",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "283",
    "vanderWallRadius": "271",
    "metallicRadius": "156",
    "covalentRadius": "196",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.657",
    "electricalConductivity": "3.6×10⁶",
    "thermalConductivity": "27",
    "crystallineStructure": "assets/BO.png",
  },
  {
    "name": "Neptunium",
    "symbol": "Np",
    "number": 93,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f4 6d1 7s2",
    "density": "20.25",
    "meltingPoint": "917",
    "boilingPoint": "4175",
    "oxidationStates": "5",
    "electronegativityPauling": "1.36",
    "electronegativityTandO": "2.35",
    "firstIonizationEnergy": "6.266",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "280",
    "vanderWallRadius": "282",
    "metallicRadius": "155",
    "covalentRadius": "190",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.897",
    "electricalConductivity": "8.3×10⁵",
    "thermalConductivity": "6",
    "crystallineStructure": "assets/SO.png",
  },
  {
    "name": "Plutonium",
    "symbol": "Pu",
    "number": 94,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f6 7s2",
    "density": "19.84",
    "meltingPoint": "913",
    "boilingPoint": "3501",
    "oxidationStates": "4",
    "electronegativityPauling": "1.28",
    "electronegativityTandO": "2.22",
    "firstIonizationEnergy": "6.06",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "278",
    "vanderWallRadius": "281",
    "metallicRadius": "159",
    "covalentRadius": "197",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.345",
    "electricalConductivity": "6.7×10⁵",
    "thermalConductivity": "6",
    "crystallineStructure": "assets/SM.png",
  },
  {
    "name": "Americium",
    "symbol": "Am",
    "number": 95,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f7 7s2",
    "density": "13.69",
    "meltingPoint": "1449",
    "boilingPoint": "2284",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.28",
    "firstIonizationEnergy": "5.993",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "276",
    "vanderWallRadius": "283",
    "metallicRadius": "173",
    "covalentRadius": "180",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "16.553",
    "electricalConductivity": "N/A",
    "thermalConductivity": "10",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Curium",
    "symbol": "Cm",
    "number": 96,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f7 6d1 7s2",
    "density": "13.51",
    "meltingPoint": "1618",
    "boilingPoint": "3400",
    "oxidationStates": "3",
    "electronegativityPauling": "1.28",
    "electronegativityTandO": "2.31",
    "firstIonizationEnergy": "6.02",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "264",
    "vanderWallRadius": "305",
    "metallicRadius": "174",
    "covalentRadius": "169",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.687",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Berkelium",
    "symbol": "Bk",
    "number": 97,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f9 7s2",
    "density": "14",
    "meltingPoint": "1323",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.08",
    "firstIonizationEnergy": "6.23",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "340",
    "metallicRadius": "170",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.041",
    "electricalConductivity": "N/A",
    "thermalConductivity": "10",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Californium",
    "symbol": "Cf",
    "number": 98,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f10 7s2",
    "density": "N/A",
    "meltingPoint": "1173",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.18",
    "firstIonizationEnergy": "6.3",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "305",
    "metallicRadius": "186",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.27",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "assets/HEX.png",
  },
  {
    "name": "Einsteinium",
    "symbol": "Es",
    "number": 99,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f11 7s2",
    "density": "N/A",
    "meltingPoint": "1133",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.29",
    "firstIonizationEnergy": "6.42",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "270",
    "metallicRadius": "186",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.501",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Fermium",
    "symbol": "Fm",
    "number": 100,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f12 7s2",
    "density": "N/A",
    "meltingPoint": "1800",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.38",
    "firstIonizationEnergy": "6.5",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.735",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Mendelevium",
    "symbol": "Md",
    "number": 101,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f13 7s2",
    "density": "N/A",
    "meltingPoint": "1100",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.47",
    "firstIonizationEnergy": "6.58",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "17.964",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Nobelium",
    "symbol": "No",
    "number": 102,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 6d1 7s2",
    "density": "N/A",
    "meltingPoint": "1100",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.06",
    "firstIonizationEnergy": "6.65",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "18.19",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Lawrencium",
    "symbol": "Lr",
    "number": 103,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 7s2 7p",
    "density": "N/A",
    "meltingPoint": "1900",
    "boilingPoint": "N/A",
    "oxidationStates": "3",
    "electronegativityPauling": "1.3",
    "electronegativityTandO": "2.1",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "15.583",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Rutherfordium",
    "symbol": "Rf",
    "number": 104,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 6d2 7s2",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "4",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.27",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "18.825",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Dubnium",
    "symbol": "Db",
    "number": 105,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 6d3 7s2",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.38",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "20.607",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Seaborgium",
    "symbol": "Sg",
    "number": 106,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 642 7s2",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.51",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "22.386",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Bohrium",
    "symbol": "Bh",
    "number": 107,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p6 5f14 6d5 7s2",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.48",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "23.36",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Hassium",
    "symbol": "Hs",
    "number": 108,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2 6p65f14 6d6 7s2",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.51",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": " N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "24.188",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Meitnerium",
    "symbol": "Mt",
    "number": 109,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.66",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "25.159",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Darmstadium",
    "symbol": "Ds",
    "number": 110,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.73",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "25.44",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Roentgenium",
    "symbol": "Rg",
    "number": 111,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.83",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": " N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "26.668",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Copernicium",
    "symbol": "Cn",
    "number": 112,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "3.03",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": " N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "28.358",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Nihonium",
    "symbol": "Nh",
    "number": 113,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.49",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "23.835",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Flerovium",
    "symbol": "Fl",
    "number": 114,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.57",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "23.952",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Moscovium",
    "symbol": "Mc",
    "number": 115,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.21",
    "firstIonizationEnergy": "N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "18.858",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Livermorium",
    "symbol": "Lv",
    "number": 116,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.42",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "20.984",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Tennessine",
    "symbol": "Ts",
    "number": 117,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.61",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "22.716",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
    "crystallineStructure": "N/A",
  },
  {
    "name": "Oganesson",
    "symbol": "Og",
    "number": 118,
    "aMass": NaN,
    "amassunc": "N/A",
    "eConfig": "",
    "density": "N/A",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "oxidationStates": "N/A",
    "electronegativityPauling": "N/A",
    "electronegativityTandO": "2.59",
    "firstIonizationEnergy": " N/A",
    "valenceAtomicRadiusRDK": "",
    "valenceAtomicRadiusClement": "",
    "R001AtomicRadius": "N/A",
    "vanderWallRadius": "N/A",
    "metallicRadius": "N/A",
    "covalentRadius": "N/A",
    "valenceEffectiveNuclearChargeRDK": "",
    "valenceEffectiveNuclearChargeGuerra": "24.366",
    "electricalConductivity": "N/A",
    "thermalConductivity": "N/A",
   "crystallineStructure": "N/A"
,   }
];
